application: crs-o-matic
version: 3
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.2"

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /.*
  script: main.py
