runtime: python37
instance_class: f4_highmem
entrypoint: gunicorn --bind :$PORT --workers 8 --timeout 120 main:app

handlers:

- url: /static
  static_dir: static

- url: /.*
  secure: always
  script: auto
